### ISSUE TITLE
why copy.deepcopy()?

### ISSUE THREAD

**Issue by damonlynch** [z3ntu/QtWaitingSpinner#1]
Is there a special reason to call copy.deepcopy? The alternative is to use QColor(colorinput) to make a copy of the color.

**Comment by z3ntu** [comment]
If `QColor(colorinput)` works, it is fine, so no special meaning behind exactly `copy.deepcopy(...)`. You just have to copy the object as you would modify the original object else. (that was a big problem when I ported it)

**Comment by damonlynch** [comment]
Yes, if you don't make a copy of the color, the original will also be changed. That's exactly how Qt works: http://doc.qt.io/qt-5/qcolor.html#QColor-6 
May I suggest making a change in the code, to make it more Qt like? I'd fork it myself but to be honest I'm totally unfamiliar with using git for even extremely  elementary commands, and now is not a good time for me to figure it out.

**Comment by z3ntu** [comment]
So you mean [line 193](https://github.com/z3ntu/QtWaitingSpinner/blob/master/waitingspinnerwidget.py#L193) should be

```
color = QColor(colorinput)
```

?

**Comment by damonlynch** [comment]
Yes exactly.
