### ISSUE TITLE
Python 2 compatibility and this widget changes the main window size (?)

### ISSUE THREAD

**Issue by iruletheworld** [z3ntu/QtWaitingSpinner#3]
When I ran this code in Python 2.7, the `super` function required arguments, so, I had to change it to :

```
class QtWaitingSpinner(QWidget):
    def __init__(self, parent, centerOnParent=True, disableParentWhenSpinning=False, modality=Qt.NonModal):
        super(QtWaitingSpinner, self).__init__(parent)
```

Also, when this widget is activated, it changes the size of my main window a bit (wider), do you know why?

**Comment by z3ntu** [comment]
Python 2 is long EOL now and compatibility is not a goal here. Closing.
