### ISSUE TITLE
Spinner + Text

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [z3ntu/QtWaitingSpinner#4]
Hi.
I have configured some changes to include text next to the spinner like this : 
![image](https://user-images.githubusercontent.com/36672242/91253680-0234a700-e726-11ea-87df-5593055638aa.png)

At the moment the text can be configured like this:

- Custom text
- Font Color 
- Font Family
- Font Size
- Font Weight
- Text Visibility

Although there is still much room for improvement, I think it can be a good starting point for those who need something like that. In my case I configured it specifically to show the process that is being carried out in a QTableView associated with a database.

Would you like me to do a PR?

**Comment by z3ntu** [comment]
I don't really want to diverge from the functionality the "upstream" C++ version provides. I think it would be best if you put it into your own repo where people can use it if they like.

**Comment by Valdes-Tresanco-MS** [comment]
I get it.
Recently when reviewing the version of c ++ I saw that there is a PR with the same functionality that have not been merged with the master branch.
So, I will put it in my repository with its respective license and reference.
Best wishes

**Comment by z3ntu** [comment]
Good luck!
