### ISSUE TITLE
Python 3.10.1 unexpected type 'float'

### ISSUE THREAD

**Issue by FrankM64** [z3ntu/QtWaitingSpinner#5]
I am using your waitingspinnerwidget in an project, works fine. Thanks! This project run with python 3.8.10.

Now i have test my project with 3.10.1 and i got some errors

Example: TypeError: setInterval/self, int): argument 1 has unexpected type 'float'

With these fixes it works as expected.

81 painter.drawRoundedRect(QRect(0, int(-self._lineWidth / 2), self._lineLength, self._lineWidth), self._roundness,
82                                    self._roundness, Qt.RelativeSize)

181 def updateTimer(self):
182       self._timer.setInterval(int(1000 / (self._numberOfLines * self._revolutionsPerSecond)))

184 def updatePosition(self):
185    if self.parentWidget() and self._centerOnParent:
186       self.move(int(self.parentWidget().width() / 2 - self.width() / 2),
187                 int(self.parentWidget().height() / 2 - self.height() / 2))

186 self.move(int(self.parentWidget().width() / 2 - self.width() / 2),
187                      int(self.parentWidget().height() / 2 - self.height() / 2))

I'm new to python and don't know if this solves all the problems now. It solved mine, I think so...

Greetings
Frank

**Comment by z3ntu** [comment]
Thanks for reporting, this should be fixed with the latest commit on git.

**Comment by FrankM64** [comment]
Thanks, tested - worked
